// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryMenuFilters } from "./LibraryMenuFilters";

export type SongTarget =
  | { kind: "hashes"; hashes: Array<string> }
  | { kind: "filter"; filters: LibraryMenuFilters };
