// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongSortColumn } from "./SongSortColumn";
import type { SortDirection } from "./SortDirection";

export type SongSort = { column: SongSortColumn; direction: SortDirection };
