// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Song } from "./Song";

export type SongsStore = {
  count: number;
  folder: string;
  processed: Array<Song>;
  processed_count: number;
  /**
   * Count of songs matching the current filter that are already analyzed
   * -- lets the frontend gate analyzed-only bulk actions (e.g. full
   * reanalysis, refetch lyrics & align) without paging in every song in
   * the filtered set.
   */
  analyzed_count: number;
};
